import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ur' | 'sd';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    overview: 'Overview',
    cashManagement: 'Cash Management',
    businesses: 'Businesses',
    assets: 'Assets',
    expenses: 'Home Expenses',
    settings: 'Settings',
    totalCash: 'Total Cash in Hand',
    totalAssets: 'Total Assets Value',
    netProfit: 'Net Profit',
    newEntry: 'New Entry',
    addAsset: 'Add Asset',
    logExpense: 'Log Expense',
    welcomeBack: 'Welcome back',
    signOut: 'Sign Out',
    liquidAssets: 'Liquid Assets Summary',
    search: 'Search...',
    save: 'Save Changes',
    cancel: 'Cancel',
    businessInvestments: 'Business Investments',
    stocks: 'Stock Market',
    bankBalance: 'Bank Balance',
    homeCash: 'Home Cash',
    addBusiness: 'Add New Business',
    businessName: 'Business Name',
    creating: 'Creating...',
    active: 'Active',
    setupFields: 'Setup Fields',
    entries: 'Entries',
    reports: 'Reports',
    fieldName: 'Field Name',
    fieldType: 'Field Type',
    accounting: 'Accounting',
    addEntry: 'Add Entry',
    exportCSV: 'Export CSV',
    totalEntries: 'Total Entries',
    lastActivity: 'Last Activity',
    noEntries: 'No entries found.',
    property: 'Property',
    vehicle: 'Vehicle',
    gold: 'Gold',
    other: 'Other',
    category: 'Category',
    amount: 'Amount',
    date: 'Date',
    notes: 'Notes',
    food: 'Food & Grocery',
    rent: 'Rent/Mortgage',
    utilities: 'Bills & Utilities',
    health: 'Health/Medical',
    transport: 'Transport/Fuel',
    cashManagementDesc: 'Manage your liquid assets and cash in hand.',
    businessInvestmentsDesc: 'Cash currently tied up in business operations.',
    stocksDesc: 'Total value of your stocks and shares.',
    bankBalanceDesc: 'Total cash available in all bank accounts.',
    homeCashDesc: 'Physical cash available at home or in hand.',
    fieldConfig: 'Field Configuration',
    fieldConfigDesc: 'Define the information you want to track for each entry in this business.',
    currentFields: 'Current Fields',
    noFieldsDefined: 'No fields defined yet. Add fields to start making entries.',
    saveConfig: 'Save Configuration',
    pleaseSetupFields: 'Please setup fields first to make entries.',
    goToSetup: 'Go to Setup',
    chooseFile: 'Choose File',
    searchBy: 'Search By...',
    searchEntries: 'Search entries...',
    noEntriesFound: 'No entries found.',
    performanceReports: 'Performance Reports',
    performanceReportsDesc: 'Generate and download detailed reports for this business.',
    startDate: 'Start Date',
    endDate: 'End Date',
    applyFilter: 'Apply Filter',
    status: 'Status',
    role: 'Role',
    owner: 'Owner',
    text: 'Text',
    number: 'Number',
    file: 'File',
    neutral: 'Neutral',
    income: 'Income (+)',
    expense: 'Expense (-)'
  },
  ur: {
    dashboard: 'ڈیش بورڈ',
    overview: 'جائزہ',
    cashManagement: 'نقد انتظام',
    businesses: 'کاروبار',
    assets: 'اثاثے',
    expenses: 'گھریلو اخراجات',
    settings: 'ترتیبات',
    totalCash: 'کل نقد رقم',
    totalAssets: 'اثاثوں کی کل مالیت',
    netProfit: 'کل منافع',
    newEntry: 'نئی انٹری',
    addAsset: 'اثاثہ شامل کریں',
    logExpense: 'اخراجات درج کریں',
    welcomeBack: 'خوش آمدید',
    signOut: 'لاگ آؤٹ',
    liquidAssets: 'نقد اثاثوں کا خلاصہ',
    search: 'تلاش کریں...',
    save: 'تبدیلیاں محفوظ کریں',
    cancel: 'منسوخ کریں',
    businessInvestments: 'کاروباری سرمایہ کاری',
    stocks: 'اسٹاک مارکیٹ',
    bankBalance: 'بینک بیلنس',
    homeCash: 'گھر پر نقد رقم',
    addBusiness: 'نیا کاروبار شامل کریں',
    businessName: 'کاروبار کا نام',
    creating: 'تیار ہو رہا ہے...',
    active: 'فعال',
    setupFields: 'فیلڈز سیٹ اپ',
    entries: 'اندراجات',
    reports: 'رپورٹس',
    fieldName: 'فیلڈ کا نام',
    fieldType: 'فیلڈ کی قسم',
    accounting: 'اکاؤنٹنگ',
    addEntry: 'اندراج شامل کریں',
    exportCSV: 'ایکسپورٹ CSV',
    totalEntries: 'کل اندراجات',
    lastActivity: 'آخری سرگرمی',
    noEntries: 'کوئی اندراج نہیں ملا۔',
    property: 'جائیداد',
    vehicle: 'گاڑی',
    gold: 'سونا',
    other: 'دیگر',
    category: 'قسم',
    amount: 'رقم',
    date: 'تاریخ',
    notes: 'نوٹس',
    food: 'کھانا اور راشن',
    rent: 'کرایہ',
    utilities: 'بل',
    health: 'صحت',
    transport: 'ٹرانسپورٹ',
    cashManagementDesc: 'اپنے نقد اثاثوں کا انتظام کریں۔',
    businessInvestmentsDesc: 'کاروبار میں لگی ہوئی نقد رقم۔',
    stocksDesc: 'آپ کے حصص اور اسٹاک کی کل مالیت۔',
    bankBalanceDesc: 'بینک کھاتوں میں موجود کل نقد رقم۔',
    homeCashDesc: 'گھر میں موجود نقد رقم۔',
    fieldConfig: 'فیلڈ کی ترتیب',
    fieldConfigDesc: 'اس کاروبار کے ہر اندراج کے لیے وہ معلومات متعین کریں جسے آپ ٹریک کرنا چاہتے ہیں۔',
    currentFields: 'موجودہ فیلڈز',
    noFieldsDefined: 'ابھی تک کوئی فیلڈ متعین نہیں ہے۔ اندراج شروع کرنے کے لیے فیلڈز شامل کریں۔',
    saveConfig: 'ترتیب محفوظ کریں',
    pleaseSetupFields: 'اندراج کرنے کے لیے براہ کرم پہلے فیلڈز سیٹ اپ کریں۔',
    goToSetup: 'سیٹ اپ پر جائیں',
    chooseFile: 'فائل کا انتخاب کریں',
    searchBy: 'تلاش بذریعہ...',
    searchEntries: 'اندراجات تلاش کریں...',
    noEntriesFound: 'کوئی اندراج نہیں ملا۔',
    performanceReports: 'کارکردگی کی رپورٹس',
    performanceReportsDesc: 'اس کاروبار کے لیے تفصیلی رپورٹس بنائیں اور ڈاؤن لوڈ کریں۔',
    startDate: 'تاریخ آغاز',
    endDate: 'تاریخ اختتام',
    applyFilter: 'فلٹر لگائیں',
    status: 'حالت',
    role: 'کردار',
    owner: 'مالک',
    text: 'متن',
    number: 'عدد',
    file: 'فائل',
    neutral: 'غیر جانبدار',
    income: 'آمدنی (+)',
    expense: 'خرچہ (-)'
  },
  sd: {
    dashboard: 'ڊيش بورڊ',
    overview: 'جائزو',
    cashManagement: 'نقد انتظام',
    businesses: 'کاروبار',
    assets: 'اثاثا',
    expenses: 'گھريلو خرچ',
    settings: 'سيٽنگون',
    totalCash: 'ڪل نقد رقم',
    totalAssets: 'اثاثن جي ڪل ماليت',
    netProfit: 'ڪل منافعو',
    newEntry: 'نئين انٽري',
    addAsset: 'اثاثو شامل ڪريو',
    logExpense: 'خرچ درج ڪريو',
    welcomeBack: 'ڀلي ڪري آيا',
    signOut: 'لاگ آئوٽ',
    liquidAssets: 'نقد اثاثن جو خلاصو',
    search: 'ڳولھيو...',
    save: 'تبديليون محفوظ ڪريو',
    cancel: 'رد ڪريو',
    businessInvestments: 'کاروباري سيڙپڪاري',
    stocks: 'اسٽاڪ مارڪيٽ',
    bankBalance: 'بئنڪ بيلنس',
    homeCash: 'گھر ۾ نقد رقم',
    addBusiness: 'نئون کاروبار شامل ڪريو',
    businessName: 'کاروبار جو نالو',
    creating: 'تيار ٿي رهيو آهي...',
    active: 'فعال',
    setupFields: 'فيلڊ سيٽ اپ',
    entries: 'اندراج',
    reports: 'رپورٽون',
    fieldName: 'فيلڊ جو نالو',
    fieldType: 'فيلڊ جو قسم',
    accounting: 'اکائونٽنگ',
    addEntry: 'اندراج شامل ڪريو',
    exportCSV: 'ايڪسپورٽ CSV',
    totalEntries: 'ڪل اندراج',
    lastActivity: 'آخري سرگرمي',
    noEntries: 'ڪو به اندراج نه مليو.',
    property: 'ملڪيت',
    vehicle: 'گاڏي',
    gold: 'سون',
    other: 'ٻيا',
    category: 'قسم',
    amount: 'رقم',
    date: 'تاريخ',
    notes: 'نوٽس',
    food: 'کاڌو ۽ راشن',
    rent: 'ڀاڙو',
    utilities: 'بل',
    health: 'صحت',
    transport: 'ٽرانسپورٽ',
    cashManagementDesc: 'پنهنجي نقد اثاثن جو انتظام ڪريو.',
    businessInvestmentsDesc: 'کاروبار ۾ لڳل نقد رقم.',
    stocksDesc: 'توهان جي شيئرز ۽ اسٽاڪ جي ڪل ماليت.',
    bankBalanceDesc: 'بئنڪ اڪائونٽس ۾ موجود ڪل نقد رقم.',
    homeCashDesc: 'گھر ۾ موجود نقد رقم.',
    fieldConfig: 'فيلڊ جي ترتيب',
    fieldConfigDesc: 'هن کاروبار جي هر اندراج لاءِ اها معلومات بيان ڪريو جيڪا توهان ٽريڪ ڪرڻ چاهيو ٿا.',
    currentFields: 'موجوده فيلڊز',
    noFieldsDefined: 'اڃا تائين ڪي به فيلڊ مقرر نه آهن. اندراج شروع ڪرڻ لاءِ فيلڊز شامل ڪريو.',
    saveConfig: 'ترتيب محفوظ ڪريو',
    pleaseSetupFields: 'اندراج ڪرڻ لاءِ مهرباني ڪري پهريان فيلڊز سيٽ اپ ڪريو.',
    goToSetup: 'سيٽ اپ تي وڃو',
    chooseFile: 'فائل چونڊيو',
    searchBy: 'ڳولھيو ذريعي...',
    searchEntries: 'اندراج ڳولھيو...',
    noEntriesFound: 'ڪو به اندراج نه مليو.',
    performanceReports: 'ڪارڪردگي جون رپورٽون',
    performanceReportsDesc: 'هن کاروبار لاءِ تفصيلي رپورٽون ٺاهيو ۽ ڊائون لوڊ ڪريو.',
    startDate: 'شروعاتي تاريخ',
    endDate: 'آخري تاريخ',
    applyFilter: 'فلٽر لڳايو',
    status: 'حالت',
    role: 'ڪردار',
    owner: 'مالڪ',
    text: 'متن',
    number: 'عدد',
    file: 'فائل',
    neutral: 'غير جانبدار',
    income: 'آمدني (+)',
    expense: 'خرچ (-)'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>((localStorage.getItem('lang') as Language) || 'en');

  useEffect(() => {
    localStorage.setItem('lang', language);
    document.dir = (language === 'ur' || language === 'sd') ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => translations[language][key] || key;
  const isRTL = language === 'ur' || language === 'sd';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
